# Generated by Django 4.1.4 on 2022-12-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("opt1", models.CharField(max_length=200)),
                ("opt2", models.CharField(max_length=200)),
                ("opt3", models.CharField(max_length=200)),
                ("opt4", models.CharField(max_length=200)),
                ("ans", models.CharField(max_length=200)),
            ],
        ),
    ]
